# Complete Docker Compose Stack for Enhanced Multi-Agent System
version: '3.8'

services:
  # Main Multi-Agent Application
  multiagent-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: multiagent-postgres-analysis
    ports:
      - "8501:8501"  # Streamlit web interface
      - "8000:8000"  # MCP server
      - "9090:9090"  # Metrics endpoint
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
      - LOG_LEVEL=INFO
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./logs:/app/logs
      - multiagent_data:/app/data
    depends_on:
      - postgres-test
      - redis
      - prometheus
    restart: unless-stopped
    networks:
      - multiagent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Test PostgreSQL Database (for development/testing)
  postgres-test:
    image: postgres:15-alpine
    container_name: multiagent-postgres-test
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - multiagent-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: multiagent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    networks:
      - multiagent-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: multiagent-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - multiagent-network
    depends_on:
      - multiagent-app

  # Grafana for metrics visualization
  grafana:
    image: grafana/grafana:latest
    container_name: multiagent-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    restart: unless-stopped
    networks:
      - multiagent-network
    depends_on:
      - prometheus

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: multiagent-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - multiagent-network
    depends_on:
      - multiagent-app
      - grafana

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  multiagent_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  multiagent-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16